Repository Read-bird/readbird-be, pull requests merged in 2023-12, with the labels that each got.

#6 플랜 생성 기능 구현
  src/app.ts
  src/architecture/controllers/plan.controller.ts
  src/architecture/repositories/plan.repository.ts
  src/architecture/services/plan.service.ts
  src/db/models/domain/Book.ts
  src/db/models/domain/Plan.ts
  src/db/models/interface/Plan.interface.ts
  src/routers/index.ts
  src/routers/plan.route.ts
  src/test/sample.js
  src/test/sample.test.js
  src/test/unit/controllers/plan.controller.unit.test.js
  src/test/unit/repositories/plan.repository.unit.test.js
  src/test/unit/services/plan.service.unit.test.js
Labels: feat

#17 :bug: Fix: authJWT 관련 버그 수정
  src/jwt/authJWT.ts
Labels: bug

#16 :sparkles: Feat : Guest 로그인 구현
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/user.repository.ts
  src/architecture/services/user.service.ts
  src/routers/user.route.ts
Labels: feat

#18 도서 검색 기능 구현
  src/architecture/controllers/book.controller.ts
  src/architecture/controllers/plan.controller.ts
  src/architecture/repositories/book.repository.ts
  src/architecture/repositories/plan.repository.ts
  src/architecture/services/book.service.ts
  src/routers/book.route.ts
  src/routers/index.ts
Labels: feat

#19 :memo: Swagger : api 명세서 업데이트
  package-lock.json
  package.json
  src/app.ts
  src/architecture/controllers/book.controller.ts
  src/architecture/controllers/plan.controller.ts
  src/architecture/controllers/user.controller.ts
  src/routers/index.ts
  src/swagger.json
Labels: documentation

#21 플랜 수정 기능 구현
  src/app.ts
  src/architecture/controllers/plan.controller.ts
  src/architecture/repositories/plan.repository.ts
  src/architecture/services/plan.service.ts
  src/routers/plan.route.ts
  src/swagger.json
Labels: feat

#22 플랜 삭제 기능 구현
  src/architecture/controllers/plan.controller.ts
  src/architecture/repositories/plan.repository.ts
  src/architecture/services/plan.service.ts
  src/routers/plan.route.ts
  src/swagger.json
Labels: feat

#23 토큰 발급 부분 수정
  package-lock.json
  src/app.ts
  src/architecture/controllers/user.controller.ts
  src/jwt/jwt-util.ts
  src/jwt/refresh.ts
  src/package.json
Labels: documentation

#27 :memo: Swagger : Swagger 문서 업데이트
  src/architecture/controllers/book.controller.ts
  src/architecture/controllers/plan.controller.ts
Labels: documentation

#29 :zap: Fix : 플랜 생성 수정
  src/architecture/controllers/plan.controller.ts
  src/architecture/repositories/plan.repository.ts
  src/architecture/services/plan.service.ts
Labels: enhancement

#30 달성 등록 / 수정 구현
  src/architecture/controllers/record.controller.ts
  src/architecture/repositories/record.repository.ts
  src/architecture/services/record.service.ts
  src/routers/index.ts
  src/routers/record.route.ts
  src/swagger.json
Labels: feat

#34 플랜 등록, 조회 버그 수정
  src/architecture/repositories/plan.repository.ts
  src/architecture/services/plan.service.ts
  src/util/makeWeekArr.ts
Labels: bug

#37 :sparkles: Feat : 기록 초기화 - 모든 플랜 일괄 삭제 구현
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/user.repository.ts
  src/architecture/services/user.service.ts
  src/db/models/interface/Plan.interface.ts
  src/routers/user.route.ts
  src/swagger.json
Labels: feat

#38 :sparkles: Feat : 나의 서재 - 성공한 플랜 조회 구현
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/user.repository.ts
  src/architecture/services/user.service.ts
  src/routers/user.route.ts
  src/swagger.json
Labels: feat

#41 :sparkles: Feat : 삭제한 플랜 조회
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/user.repository.ts
  src/architecture/services/user.service.ts
  src/routers/user.route.ts
  src/swagger.json
Labels: feat

#42 :sparkles: Feat : 플랜 복구 구현
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/user.repository.ts
  src/architecture/services/user.service.ts
  src/routers/user.route.ts
  src/swagger.json
Labels: feat

#43 마이페이지 오류 수정
  src/architecture/repositories/user.repository.ts
  src/architecture/services/plan.service.ts
Labels: bug

#44 :zap: Fix : 버그 수정
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/plan.repository.ts
  src/architecture/services/plan.service.ts
  src/architecture/services/record.service.ts
Labels: bug

#46 :sparkles: Feat : 첫 플랜 생성 기념 캐릭터 획득 구현
  src/architecture/controllers/collection.controller.ts
  src/architecture/repositories/collection.repository.ts
  src/architecture/services/collection.service.ts
  src/routers/collection.route.ts
  src/routers/index.ts
  src/swagger.json
Labels: feat

#49 :sparkles: Feat : 유저별 도감 검색
  src/architecture/controllers/collection.controller.ts
  src/architecture/repositories/collection.repository.ts
  src/architecture/services/collection.service.ts
  src/routers/collection.route.ts
  src/swagger.json
Labels: feat

#50 :sparkles: Feat : 새로운 캐릭터 획득 구현
  src/architecture/controllers/collection.controller.ts
  src/architecture/repositories/collection.repository.ts
  src/architecture/services/collection.service.ts
  src/db/models/domain/Tables.ts
  src/db/seeders/20231210160655-Character.js
  src/routers/collection.route.ts
  src/swagger.json
Labels: feat

#51 :zap: Fix : 수정사항 업데이트
  src/architecture/controllers/collection.controller.ts
  src/architecture/controllers/plan.controller.ts
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/plan.repository.ts
  src/architecture/services/collection.service.ts
  src/architecture/services/plan.service.ts
  src/architecture/services/user.service.ts
  src/db/models/domain/Tables.ts
  src/swagger.json
Labels: feat

#53 :zap: Fix : 달성률 등록 시 플랜 완성 여부에 따라 도감 등록 구현
  src/architecture/controllers/record.controller.ts
  src/architecture/repositories/record.repository.ts
  src/architecture/services/plan.service.ts
  src/architecture/services/record.service.ts
  src/db/models/domain/Tables.ts
  src/db/seeders/20231210160655-Character.js
  src/swagger.json
Labels: feat

#54 :zap: Fix : 도감이 없을 시 에러가 나는 부분 수정
  src/architecture/services/collection.service.ts
Labels: bug

#55 회원 탈퇴 기능 추가
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/user.repository.ts
  src/architecture/services/user.service.ts
  src/routers/user.route.ts
Labels: feat

#56 :bug: Fix: email 중복값으로 인한 에러 현상 수정
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/user.repository.ts
  src/architecture/services/user.service.ts
Labels: bug

#58 :sparkles: Feat: 도서 상세페이지 기능 추가
  src/architecture/controllers/book.controller.ts
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/book.repository.ts
  src/architecture/services/book.service.ts
  src/architecture/services/user.service.ts
  src/db/models/domain/Tables.ts
  src/db/models/interface/Plan.interface.ts
  src/jwt/jwt-util.ts
  src/routers/book.route.ts
Labels: feat

#64 :sparkles: Feat: 도서 유효성 검사 기능 추가
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/user.repository.ts
  src/architecture/services/user.service.ts
  src/routers/user.route.ts
Labels: feat

#61 :sparkles: Feat: 플랜 유효성 기능 추가
  src/architecture/controllers/user.controller.ts
Labels: feat

#26 :art: Refactor: 카카오 로그인 error처리 수정
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/user.repository.ts
  src/architecture/services/user.service.ts
  src/swagger.json
Labels: bug

#60 :zap: Fix : 책 검색 기능 업그레이드
  src/architecture/controllers/book.controller.ts
  src/architecture/repositories/book.repository.ts
  src/architecture/services/book.service.ts
  src/swagger.json
Labels: bug, feat

#66 후작업 업데이트
  src/architecture/controllers/book.controller.ts
  src/architecture/controllers/collection.controller.ts
  src/architecture/controllers/record.controller.ts
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/book.repository.ts
  src/architecture/repositories/record.repository.ts
  src/architecture/services/book.service.ts
  src/architecture/services/collection.service.ts
  src/architecture/services/plan.service.ts
  src/architecture/services/record.service.ts
  src/architecture/services/user.service.ts
  src/routers/collection.route.ts
  src/routers/user.route.ts
  src/swagger.json
Labels: feat, FIx

#67 :zap: Fix : 이벤트 업데이트
  src/architecture/repositories/collection.repository.ts
  src/architecture/services/collection.service.ts
  src/architecture/services/record.service.ts
Labels: FIx

#68 :bug: Fix : 월간 달성률 수정
  src/architecture/services/record.service.ts
Labels: bug

#70 :zap: Fix : 캐릭터 획득일 추가
  src/architecture/services/collection.service.ts
  src/architecture/services/record.service.ts
Labels: FIx

#71 :bug: Fix : 플랜 복원 데이터 수정
  src/architecture/services/user.service.ts
Labels: bug

#72 :zap: Fix : 리스폰 데이터 수정 및 페이지네이션 추가
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/user.repository.ts
  src/architecture/services/user.service.ts
Labels: FIx

#73 :bug: Fix : 주간 달성률 버그 수정
  src/architecture/services/plan.service.ts
Labels: bug

#69 :memo: Feat: 최초 로그인시 캐릭터 정보를 유저 정보와 함께 반환
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/user.repository.ts
  src/architecture/services/user.service.ts
  src/db/models/domain/Tables.ts
  src/db/models/interface/Collection.interface.ts
Labels: documentation

#74 :sparkles: Feat: 인기 도서 top 10 조회 기능 구현
  src/architecture/controllers/aladin.controller.ts
  src/architecture/repositories/aladin.repository.ts
  src/package.json
  src/routers/aladin.route.ts
  src/routers/index.ts
Labels: feat

#77 ⚡ Fix : 추가 업데이트
  src/architecture/repositories/plan.repository.ts
  src/architecture/repositories/record.repository.ts
  src/architecture/services/plan.service.ts
  src/architecture/services/record.service.ts
  src/architecture/services/user.service.ts
Labels: bug, FIx

#79 :zap: Fix : 추가 업데이트
  src/architecture/controllers/plan.controller.ts
  src/architecture/repositories/plan.repository.ts
  src/architecture/repositories/user.repository.ts
  src/architecture/services/plan.service.ts
  src/architecture/services/user.service.ts
  src/routers/plan.route.ts
  src/swagger.json
  src/util/setDateFormat.ts
Labels: bug, feat, FIx

#81 :bug: Fix : 플랜 수정 타겟 값 변경
  src/architecture/services/plan.service.ts
  src/util/makeMonthArr.ts
Labels: bug

#82 :art: Feat : 공통 변수 target 유틸 생성
  src/architecture/services/plan.service.ts
  src/util/getPlanTarget.ts
Labels: feat

#84 :bug: Fix: 버그 수정 완료
  src/architecture/controllers/aladin.controller.ts
Labels: bug

#85 :bug: Fix : 이벤트 캐릭터 등록 수정
  src/architecture/controllers/plan.controller.ts
  src/architecture/services/collection.service.ts
Labels: bug

#87 [BE] 플랜 연장, 조회, 등록 api 수정
  src/architecture/repositories/plan.repository.ts
  src/architecture/services/plan.service.ts
Labels: bug, FIx

#88 :bug: Fix : 종료일에 target이 마이너스로 계산되는 문제 해결
  src/util/getPlanTarget.ts
Labels: bug

#89 :poop: Fix : 종료일 성공 타겟 수정
  src/util/getPlanTarget.ts
Labels: bug

#90 :bug: Fix : 플랜 종료일 버그 해결
  src/architecture/repositories/plan.repository.ts
  src/util/getPlanTarget.ts
Labels: bug

#91 :bug: Fix : target util 수정
  src/util/getPlanTarget.ts
Labels: bug

#92 :bug: Fix: 인기 도서 top10 중복 데이터 발생으로 인한 버그 수정
  src/architecture/controllers/aladin.controller.ts
  src/architecture/repositories/aladin.repository.ts
Labels: bug

#94 :zap: Fix : book validation 수정
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/user.repository.ts
  src/architecture/services/user.service.ts
  src/routers/user.route.ts
Labels: bug, FIx

#95 :bug: Fix : 이미지 변수명 수정
  src/architecture/services/book.service.ts
Labels: bug

#96 :zap: Fix : 이미지 사이즈 변경
  src/architecture/services/book.service.ts
Labels: FIx

#97 :zap: Fix : 이미지 사이즈 변경
  src/architecture/controllers/aladin.controller.ts
Labels: FIx

#98 :bug: Fix : 플랜 등록 오류
  src/architecture/services/plan.service.ts
Labels: bug

#99 :bug: isbn이 없는 플랜이 등록 될 때 버그 해결
  src/architecture/repositories/plan.repository.ts
  src/architecture/services/plan.service.ts
Labels: bug

#101 :bug: Fix: plan 무한 생성 버그 수정
  src/architecture/controllers/user.controller.ts
Labels: bug

#100 :memo: Docs: 인기 도서 author 정보 누락으로 추가
  src/architecture/repositories/aladin.repository.ts
Labels: documentation

#102 :bug: Fix : 플랜 연장 response 수정
  src/architecture/services/plan.service.ts
Labels: bug

#103 :poop: Fix : 코드 오타 수정
  src/architecture/services/plan.service.ts
Labels: bug

#104 :zap: Fix : 플랜 연장 시 recordStatus 추가
  src/architecture/services/plan.service.ts
Labels: FIx

#105 :art: Feat : 구매하기 링크 추가
  src/architecture/services/book.service.ts
Labels: feat

#106 :bug: Fix : 복구 한 플랜 플랜복원에 뜨지 않도록 수정
  src/architecture/services/plan.service.ts
Labels: bug

#107 :zap: Fix : 베스트셀러 link 추가
  src/architecture/controllers/aladin.controller.ts
Labels: FIx

#109 :zap: Fix : 베스트셀러 링크 데이터 추가
  src/architecture/controllers/aladin.controller.ts
Labels: bug, FIx

#110 :zap: Fix : 베스트셀러 링크 데이터 추가
  src/architecture/controllers/aladin.controller.ts
Labels: bug

#111 :zap: Fix : 베스트셀러 링크 데이터 추가
  src/architecture/controllers/aladin.controller.ts
Labels: bug

#112 :zap: Fix : 종료일 달성 실패 시 플랜 status = failed로 변경
  src/architecture/services/record.service.ts
Labels: FIx

#113 :bug: Fix : 종료일 recordStatus에 따른 planStatus 업데이트 수정
  src/architecture/services/record.service.ts
Labels: bug

#114 백엔드 코드 정리
  package-lock.json
  package.json
  src/app.ts
  src/architecture/controllers/aladin.controller.ts
  src/architecture/controllers/book.controller.ts
  src/architecture/controllers/collection.controller.ts
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/aladin.repository.ts
  src/architecture/repositories/book.repository.ts
  src/architecture/repositories/collection.repository.ts
  src/architecture/repositories/plan.repository.ts
  src/architecture/repositories/record.repository.ts
  src/architecture/repositories/user.repository.ts
  src/architecture/services/book.service.ts
  src/architecture/services/collection.service.ts
  src/architecture/services/plan.service.ts
  src/architecture/services/user.service.ts
  src/routers/collection.route.ts
  src/routers/user.route.ts
Labels: documentation

#116 :bug: Fix : 캐릭터 획득 시 while이 무한루프 되는 문제 해결
  src/architecture/controllers/collection.controller.ts
  src/architecture/controllers/record.controller.ts
  src/architecture/services/collection.service.ts
  src/architecture/services/record.service.ts
  src/routers/collection.route.ts
  src/swagger.json
Labels: bug, FIx

#117 :bug: Fix : 캐릭터 획득 버그 해결 완료
  src/architecture/controllers/record.controller.ts
  src/architecture/services/record.service.ts
Labels: bug

#118 :bug: Fix : target 및 character 문제 해결
  src/architecture/services/record.service.ts
  src/util/getPlanTarget.ts
Labels: bug

#119 :bug: Fix : 캐릭터 문제 다시 발생
  src/architecture/services/record.service.ts
Labels: bug

#120 :bug: Fix : 캐릭터 문제 다시 발생
  src/architecture/services/record.service.ts
Labels: bug

#121 :bug: Fix : 캐릭터 문제 다시 발생
  src/architecture/services/record.service.ts
Labels: bug

#122 :zap: Fix : 이미 읽은 책은 캐릭터 획득 못하도록 수정
  src/architecture/repositories/record.repository.ts
  src/architecture/services/record.service.ts
Labels: bug

#123 :pencil2: Fix : 오타 수정
  src/architecture/repositories/record.repository.ts
  src/architecture/services/record.service.ts
Labels: bug
