Repository Read-bird/readbird-be, pull requests merged in 2024-01, with the labels that each got.

#126 :art: Docs: authJWT error 처리 로직 구현
  src/jwt/authJWT.ts
Labels: documentation

#127 :bug: Fix: 게스트 로그인이 아닐 경우만 탈퇴한 회원 조회
  src/jwt/authJWT.ts
Labels: bug

#128 :loud_sound: Feat : morgan과 winston을 이용한 logging 세팅
  Jenkinsfile
  package-lock.json
  package.json
  sonar-project.properties
  src/app.ts
  src/db/config/config.ts
  src/util/logger/morgan.ts
  src/util/logger/winston.ts
Labels: feat

#129 :bug: Fix: 토큰이 null일때 서버 무한 로딩 수정
  src/architecture/controllers/user.controller.ts
  src/jwt/authJWT.ts
  src/jwt/jwt-util.ts
Labels: bug

#130 :bug: Fix: auth 토큰 발행 실패
  src/architecture/controllers/user.controller.ts
  src/jwt/authJWT.ts
Labels: bug

#131 :bug: Fix : 완독 실패 책을 성공했을 경우에는 캐릭터 제공 하도록 수정
  src/architecture/repositories/record.repository.ts
Labels: bug

#132 :zap: 배포 후 작업
  package-lock.json
  package.json
  src/app.ts
  src/util/artillery/.DS_Store
  src/util/artillery/data.csv
  src/util/artillery/loadtest.json
  src/util/artillery/results/loadtest_result.json
  src/util/artillery/results/loadtest_result.json.html
  src/util/googleSheet/getData.js
  src/util/googleSheet/google_sheets.js
  src/util/logger/winston.ts
Labels: feat

#133 :bug: Fix : 메모리 부족 개선을 위한 script 변경
  package.json
Labels: bug

#134 Create README.md
  README.md
Labels: feat

#135 :zap: Fix : 추가 업데이트
  Jenkinsfile
  package-lock.json
  package.json
  sonar-project.properties
  src/app.ts
  src/architecture/controllers/collection.controller.ts
  src/architecture/controllers/record.controller.ts
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/record.repository.ts
  src/architecture/services/collection.service.ts
  src/architecture/services/record.service.ts
  src/db/config/config.ts
  src/jwt/authJWT.ts
  src/jwt/jwt-util.ts
  src/routers/collection.route.ts
  src/swagger.json
  src/util/artillery/.DS_Store
  src/util/artillery/data.csv
  src/util/artillery/loadtest.json
  src/util/artillery/results/loadtest_result.json
  src/util/artillery/results/loadtest_result.json.html
  src/util/getPlanTarget.ts
  src/util/googleSheet/getData.js
  src/util/googleSheet/google_sheets.js
  src/util/logger/morgan.ts
  src/util/logger/winston.ts
Labels: feat

#136 :zap: Fix : 로컬호스트 origin 추가
  src/app.ts
Labels: FIx

#137 :bug: Fix : 변수 선언 위치 변경 및 함수 전달 인자 수정
  src/util/googleSheet/getData.js
  src/util/googleSheet/google_sheets.js
Labels: bug

#138 :zap: Feat : 수집 데이터 업데이트
  src/app.ts
  src/architecture/controllers/user.controller.ts
  src/architecture/repositories/user.repository.ts
  src/architecture/services/user.service.ts
  src/db/migrations/create-table/7.create-table-dailyData.ts
  src/db/models/domain/Tables.ts
  src/db/models/interface/DailyData.interface.ts
  src/jwt/authJWT.ts
  src/util/googleSheet/getData.js
  src/util/googleSheet/google_sheets.js
Labels: feat, FIx

#144 Dev update.v2
  src/architecture/controllers/plan.controller.ts
  src/architecture/repositories/plan.repository.ts
  src/architecture/services/plan.service.ts
  src/architecture/services/record.service.ts
  src/util/googleSheet/getData.js
  src/util/googleSheet/google_sheets.js
Labels: bug, FIx
